# Generated by Django 4.2 on 2023-04-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupPage',
            new_name='RegisterPage',
        ),
        migrations.AlterModelOptions(
            name='registerpage',
            options={'verbose_name': 'Register Page'},
        ),
    ]
