# Generated by Django 4.2 on 2023-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerpage',
            old_name='text_2',
            new_name='text_login',
        ),
        migrations.RenameField(
            model_name='registerpage',
            old_name='text_3',
            new_name='text_part1',
        ),
        migrations.RenameField(
            model_name='registerpage',
            old_name='text_1',
            new_name='text_part2',
        ),
        migrations.RemoveField(
            model_name='registerpage',
            name='text_4',
        ),
        migrations.AddField(
            model_name='loginpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loginpage',
            name='signup_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginpage',
            name='signup_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
