# Generated by Django 4.2 on 2023-05-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_rename_text_2_registerpage_text_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerpage',
            old_name='button_login',
            new_name='login_link',
        ),
        migrations.RenameField(
            model_name='registerpage',
            old_name='text_login',
            new_name='login_text',
        ),
    ]
