# Generated by Django 4.2 on 2023-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_alter_signuppage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpage',
            name='button',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='button_end',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='button_login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='text_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='text_4',
            field=models.TextField(blank=True),
        ),
    ]
