# Generated by Django 4.2 on 2023-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0005_alter_loginpage_button_alter_loginpage_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppage',
            name='confirmation_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signuppage',
            name='confirmation_pre',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
