# Generated by Django 4.2 on 2023-04-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True)),
                ('ending_text_1', models.TextField(blank=True)),
                ('ending_text_2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='about.aboutpage')),
            ],
        ),
    ]
