# Generated by Django 4.2 on 2023-04-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('motto', models.CharField(blank=True, max_length=100)),
                ('instruction', models.CharField(blank=True, max_length=100)),
                ('error_not_found', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
    ]
