# Generated by Django 4.2 on 2023-05-01 14:57

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(editable=False, unique=True)),
                ('audio', models.FileField(upload_to='audio')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1_instruction', ckeditor.fields.RichTextField(blank=True)),
                ('phase2_instruction', ckeditor.fields.RichTextField(blank=True)),
                ('phase3_instruction', ckeditor.fields.RichTextField(blank=True)),
                ('phase3_back', models.CharField(blank=True, max_length=20)),
                ('phase3_forward', models.CharField(blank=True, max_length=20)),
                ('phase4_instruction', ckeditor.fields.RichTextField(blank=True)),
                ('phase4_back', models.CharField(blank=True, max_length=20)),
                ('phase4_forward', models.CharField(blank=True, max_length=20)),
                ('confirmation_pre_name', models.CharField(blank=True, max_length=100)),
                ('confirmation_post_name', models.TextField(blank=True)),
                ('confirmation_regret', models.TextField(blank=True)),
                ('confirmation_remember', models.TextField(blank=True)),
                ('error_text_1', models.TextField(blank=True)),
                ('error_text_2', models.TextField(blank=True)),
                ('error_back', models.CharField(blank=True, max_length=20)),
                ('error_forward', models.CharField(blank=True, max_length=20)),
                ('success', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Record Page',
            },
        ),
    ]
