# Generated by Django 4.2 on 2023-04-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='effect',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
