# Generated by Django 4.2 on 2023-04-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_effect_options_effect_the_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpage',
            name='error_back',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='error_forward',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
