# Generated by Django 4.2 on 2023-05-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase1_instruction',
            new_name='step1_instruction',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase2_instruction',
            new_name='step2_instruction',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase3_back',
            new_name='step3_back',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase3_forward',
            new_name='step3_forward',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase3_instruction',
            new_name='step3_instruction',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase4_back',
            new_name='step4_back',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase4_forward',
            new_name='step4_forward',
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='phase4_instruction',
            new_name='step4_instruction',
        ),
    ]
