# Generated by Django 4.2 on 2023-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='recordpage',
            old_name='success',
            new_name='delete_success',
        ),
        migrations.AddField(
            model_name='recordpage',
            name='confirmation_generating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='delete_ko',
            field=models.TextField(blank=True),
        ),
    ]
